### ISSUE TITLE
Promini not supported

### ISSUE THREAD

**Issue by ajfisher** [ajfisher/nodebots-interchange#7]
Make sure promini is supported board type. Possible support need from avrgirl or possibly need to update avrgirl within interchange if it is supported.

Ping @noopkat for her wisdom too.

Raised by @frxnz here: https://gist.github.com/frxnz/1c9363e34ec297f31eb4

**Comment by ajfisher** [comment]
Issue is naming convention uses 'promini' instead of 'pro-mini' will update and roll out to downstream packages.

**Comment by noopkat** [comment]
if it would be helpful, within avrgirl-arduino I can map some 'mispells' to the proper conventions. This way we could support hyphenated and non hyphenated versions, which isn't really much overhead for me to maintain going forward. I can see this catching a lot of folks out for future dependents of avrgirl

**Comment by ajfisher** [comment]
I think that's a great idea - though this was a definite "user error" problem, accounting for developer vagueness on common mispells would be a nice touch for sure...

**Comment by ajfisher** [comment]
wontfix is here because it's an issue in the upstream interchange repos not one inherent to interchange itself as avrgirl supports promini as a board.

**Comment by ajfisher** [comment]
Closing this now that I've patched the upstreams.
